[workspace]
members = ["cli", "lib"]

# These bits are copied from rpm-ostree.
[profile.dev]
opt-level = 1 # No optimizations are too slow for us.

[profile.release]
lto = "thin"

[patch.crates-io]
tar = { path = "../../alexcrichton/tar-rs" }